---
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: Install Docker 
  ansible.builtin.apt:
    name:
      - docker-ce=5:27.2.0-1~ubuntu.24.04~noble
      - docker-ce-cli=5:27.2.0-1~ubuntu.24.04~noble
      - containerd.io
    state: present
    update_cache: true

- name: Setup docker user
  ansible.builtin.user:
    name: docker
    groups: "docker,sudo"
    append: true

- name: install python dependencies
  become: true
  apt:
    update_cache: yes
    state: latest
    name: python3-pip

- name: Install docker
  remote_user: ubuntu
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: yes

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true

